/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17695 2009-07-21 12:22:18Z dts12 $
 */
#ifndef STORAGE_H
#define STORAGE_H

/* function declarations */
void init_storage(void);
void initialize_table_SystemIfTable(void);
Netsnmp_Node_Handler SystemIfTable_handler;
Netsnmp_First_Data_Point  SystemIfTable_get_first_data_point;
Netsnmp_Next_Data_Point   SystemIfTable_get_next_data_point;
void initialize_table_SystemHdTable(void);
Netsnmp_Node_Handler SystemHdTable_handler;
Netsnmp_First_Data_Point  SystemHdTable_get_first_data_point;
Netsnmp_Next_Data_Point   SystemHdTable_get_next_data_point;
void initialize_table_SystemFanTable(void);
Netsnmp_Node_Handler SystemFanTable_handler;
Netsnmp_First_Data_Point  SystemFanTable_get_first_data_point;
Netsnmp_Next_Data_Point   SystemFanTable_get_next_data_point;
void initialize_table_SystemVolumeTable(void);
Netsnmp_Node_Handler SystemVolumeTable_handler;
Netsnmp_First_Data_Point  SystemVolumeTable_get_first_data_point;
Netsnmp_Next_Data_Point   SystemVolumeTable_get_next_data_point;

void initialize_table_SystemCpuTable(void);
Netsnmp_Node_Handler SystemCpuTable_handler;
Netsnmp_First_Data_Point  SystemCpuTable_get_first_data_point;
Netsnmp_Next_Data_Point   SystemCpuTable_get_next_data_point;

void initialize_table_SystemMemoryTable(void);
Netsnmp_Node_Handler SystemMemoryTable_handler;
Netsnmp_First_Data_Point  SystemMemoryTable_get_first_data_point;
Netsnmp_Next_Data_Point   SystemMemoryTable_get_next_data_point;

/* column number definitions for table SystemIfTable */
       #define COLUMN_IFINDEX		5
       #define COLUMN_IFDESCR		6
       #define COLUMN_IFIPADDR	1
       #define COLUMN_IFLINKED	2
       #define COLUMN_IFPACKETSRECEIVED		3
       #define COLUMN_IFPACKETSSENT		4
       #define COLUMN_IFERRORPACKETS		7

/* column number definitions for table SystemHdTable */
       #define COLUMN_HDINDEX		21
       #define COLUMN_HDUUID		1
       #define COLUMN_MOUNTED		2
       #define COLUMN_CANWRITE		3
       #define COLUMN_MOUNTPATH		4
       #define COLUMN_READ_RATE		8
       #define COLUMN_WRITE_RATE	9
       #define COLUMN_HDDESCR		5
       #define COLUMN_HDTEMPERATURE		10
       #define COLUMN_HDSTATUS		24
       #define COLUMN_HDMODEL		25
       #define COLUMN_HDCAPACITY		6
       #define COLUMN_HDUSEDSIZE		7
       #define COLUMN_HDSMARTINFO	27

/* column number definitions for table SystemFanTable */
       #define COLUMN_SYSFANINDEX		1
       #define COLUMN_SYSFANDESCR		2
       #define COLUMN_SYSFANSTATUS		3
       #define COLUMN_SYSFANSPEED		4

/* column number definitions for table SystemVolumeTable */
       #define COLUMN_SYSVOLUMEINDEX               1
       #define COLUMN_SYSVOLUMEDESCR               2
       #define COLUMN_SYSVOLUMEFS                  3
       #define COLUMN_SYSVOLUMETOTALSIZE           4
       #define COLUMN_SYSVOLUMEFREESIZE            5
       #define COLUMN_SYSVOLUMESTATUS              6

/* column number definitions for table SystemCpuTable */
       #define COLUMN_CPUINDEX		10
       #define COLUMN_CPURUNTIME	1
       #define COLUMN_CPUUSAGE		2
       #define COLUMN_CPUUSER		3
       #define COLUMN_CPUSYSTEM		4
       #define COLUMN_CPUIDLE		5
       #define COLUMN_CPUIOWAIT		6
       #define COLUMN_CPUNAME		7
       #define COLUMN_CPUTEMPERATURE	8
       #define COLUMN_CPUSPEED		9

/* column number definitions for table SystemMemoryTable */
       #define COLUMN_MEMORY_TOTAL	1
       #define COLUMN_MEMORY_VTOTAL	2
       #define COLUMN_MEMORY_USED	3
       #define COLUMN_MEMORY_VUSED	4

#endif /* STORAGE_H */
