/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 17337 2009-01-01 14:28:29Z magfr $
 */
#ifndef SYSTEMINFO_H
#define SYSTEMINFO_H

/* function declarations */
void init_SystemInfo(void);
Netsnmp_Node_Handler handle_SystemCPU_Usage;
Netsnmp_Node_Handler handle_SystemTotalMem;
Netsnmp_Node_Handler handle_SystemFreeMem;
Netsnmp_Node_Handler handle_SystemUptime;
Netsnmp_Node_Handler handle_CPU_Temperature;
Netsnmp_Node_Handler handle_SystemTemperature;
Netsnmp_Node_Handler handle_IfNumber;
Netsnmp_Node_Handler handle_HdNumber;
Netsnmp_Node_Handler handle_ModelName;
Netsnmp_Node_Handler handle_HostName;
Netsnmp_Node_Handler handle_SysFanNumber;
Netsnmp_Node_Handler handle_SysVolumeNumber;

#endif /* SYSTEMINFO_H */
