#
# Makefile
#
# Version:	$Id: Makefile,v 1.1.1.1 2010/03/11 07:11:43 richardchang Exp $
#

TARGET		= rlm_policy
SRCS		= rlm_policy.c parse.c evaluate.c
HEADERS		= rlm_policy.h
RLM_CFLAGS	=
RLM_LIBS	=

include ../rules.mak

$(LT_OBJS): $(HEADERS)
