/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 17337 2009-01-01 14:28:29Z magfr $
 */
#ifndef SYSTEMINFOEX_H
#define SYSTEMINFOEX_H

/* function declarations */
void init_SystemInfoEx(void);
Netsnmp_Node_Handler handle_SystemCPU_UsageEx;
Netsnmp_Node_Handler handle_SystemTotalMemEx;
Netsnmp_Node_Handler handle_SystemFreeMemEx;
Netsnmp_Node_Handler handle_SystemUptimeEx;
Netsnmp_Node_Handler handle_CPU_TemperatureEx;
Netsnmp_Node_Handler handle_SystemTemperatureEx;
Netsnmp_Node_Handler handle_IfNumberEx;
Netsnmp_Node_Handler handle_HdNumberEx;
Netsnmp_Node_Handler handle_ModelNameEx;
Netsnmp_Node_Handler handle_HostNameEx;
Netsnmp_Node_Handler handle_SysFanNumberEx;
Netsnmp_Node_Handler handle_SysVolumeNumberEx;

#endif /* SYSTEMINFOEX_H */
