CFILES = hfs_endian.c makehfs.c newfs_hfs.c
OFILES = $(CFILES:.c=.o)

all: newfs_hfs

newfs_hfs: $(OFILES)
	${CC} ${CFLAGS} -o newfs_hfs ${OFILES} -lssl -lcrypto -L$(TARGET_PREFIX)/lib -L$(TARGET_PREFIX)/usr/lib

clean:
	$(RM) newfs_hfs $(OFILES)

.PHONY : FORCE clean
