'\" t
.\"     Title: faillog
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.74.3 <http://docbook.sf.net/>
.\"      Date: 05/10/2009
.\"    Manual: Форматы файлов
.\"    Source: Форматы файлов
.\"  Language: Russian
.\"
.TH "faillog" "5" "05/10/2009" "Форматы файлов" "Форматы файлов"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
faillog \- файл протокола неудачных попыток входа в систему
.SH "ОПИСАНИЕ"
.PP
В файле
/var/log/faillog
хранится число неудачных попыток входа в систему и их предельное число для каждой учётной записи\&. Этот файл состоит из записей постоянной длины, упорядоченных по числовому идентификатору учётной записи\&. Каждая запись содержит число неудачных попыток входа с момента последнего успешного входа в систему, максимальное число неудачных попыток перед тем как учётная запись будет заблокирована, терминал, с которого осуществлялась последняя неудачная попытка входа, дату этого события и интервал в секундах на сколько учётная запись будет заблокирована в случае неудачной регистрации\&.
.PP
Структура файла:
.sp
.if n \{\
.RS 4
.\}
.nf
struct	faillog {
	short   fail_cnt;
	short   fail_max;
	char    fail_line[12];
	time_t  fail_time;
	long    fail_locktime;
};
.fi
.if n \{\
.RE
.\}
.SH "ФАЙЛЫ"
.PP
/var/log/faillog
.RS 4
содержит журнал неудавшихся попыток входа в систему
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP

\fBfaillog\fR(8)
