'\" t
.\"     Title: pwck
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.74.3 <http://docbook.sf.net/>
.\"      Date: 05/10/2009
.\"    Manual: Команды управления системой
.\"    Source: Команды управления системой
.\"  Language: Russian
.\"
.TH "pwck" "8" "05/10/2009" "Команды управления системой" "Команды управления системой"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
pwck \- проверяет целостность файлов паролей
.SH "СИНТАКСИС"
.HP \w'\fBpwck\fR\ 'u
\fBpwck\fR [\-q] [\-s] [\fIpasswd\fR\ [\ \fIshadow\fR\ ]]
.HP \w'\fBpwck\fR\ 'u
\fBpwck\fR [\-q] [\-r] [\fIpasswd\fR\ \fIshadow\fR]
.SH "ОПИСАНИЕ"
.PP
Программа
\fBpwck\fR
проверяет корректность аутентификационной информации в системе\&. Проверяется формат всех записей файлов
/etc/passwd
и
/etc/shadow
и допустимость данных каждого поля\&. В случае обнаружения ошибок пользователю предлагается подтвердить удаление записей, имеющих неверный формат или восстановление которых невозможно\&.
.PP
Выполняются следующие проверки:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
правильное количество полей
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
уникальность имени пользователя
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
допустимость идентификатора пользователя и группы
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
допустимость первичной группы
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
допустимость домашнего каталога
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
допустимость регистрационной оболочки
.RE
.PP
Ошибки в количестве полей и уникальности имён пользователей невосстановимы\&. Если запись содержит неверное число полей, пользователя попросят подтвердить удаление всей записи\&. Если пользователь ответит отрицательно, дальнейшая проверка выполняться не будет\&. При ошибке повторения имени пользователя также возникает запрос на удаление, но в случае отказа проверка будет продолжена\&. Обо всех остальных ошибках выводится предупреждение и пользователю предлагается запустить команду
\fBusermod\fR, чтобы исправить ошибку\&.
.PP
Команды, которые работают с файлом
/etc/passwd
не могут изменять повреждённые или дублирующиеся записи\&. Как раз в этом случае и нужно использовать
\fBpwck\fR
для удаления испорченной записи\&.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBpwck\fR:
.PP
\fB\-q\fR
.RS 4
Сообщать только об ошибках\&. Предупреждения, которые не требуют от пользователя никаких действий, показаны не будут\&.
.RE
.PP
\fB\-r\fR
.RS 4
Выполнять команду
\fBpwck\fR
в режиме "только чтение"\&.
.RE
.PP
\fB\-s\fR
.RS 4
Отсортировать все записи в файлах
/etc/passwd
и
/etc/shadow
по числовому идентификатору пользователя\&.
.RE
.PP
По умолчанию, команда
\fBpwck\fR
работает с файлами
/etc/passwd
и
/etc/shadow\&. Пользователь может указать другие файлы с помощью параметров
\fIpasswd\fR
и
\fIshadow\fR
.SH "CONFIGURATION"
.PP
The following configuration variables in
/etc/login\&.defs
change the behavior of this tool:
.PP
\fBPASS_MAX_DAYS\fR (number)
.RS 4
Максимальное число дней использования пароля\&. Если пароль старее этого числа, то будет запущена процедура смены пароля\&. Если значение не задано, то предполагается значение \-1 (то есть возможность ограничения не используется)\&.
.RE
.PP
\fBPASS_MIN_DAYS\fR (number)
.RS 4
Максимальное число дней между изменениями пароля\&. Любая смена пароля ранее заданного срока выполнена не будет\&. Если значение не задано, то предполагается значение \-1 (то есть возможность ограничения не используется)\&.
.RE
.PP
\fBPASS_WARN_AGE\fR (number)
.RS 4
Число дней за которое начнёт выдаваться предупреждение об устаревании пароля\&. Нулевое значение означает, что предупреждение выдаётся в день устаревания, при отрицательном значении предупреждение выдаваться не будет\&. Если значение не задано, выдача предупреждения отключается\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/group
.RS 4
содержит информацию о группах
.RE
.PP
/etc/passwd
.RS 4
содержит информацию о пользователях
.RE
.PP
/etc/shadow
.RS 4
содержит защищаемую информацию о пользователях
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP

\fBgroup\fR(5),
\fBgrpck\fR(8),
\fBpasswd\fR(5),
\fBshadow\fR(5),
\fBusermod\fR(8)\&.
.SH "ВОЗВРАЩАЕМЫЕ ЗНАЧЕНИЯ"
.PP
Команда
\fBpwck\fR
завершая работу, возвращает следующие значения:
.PP
\fI0\fR
.RS 4
успешное выполнение
.RE
.PP
\fI1\fR
.RS 4
ошибка в параметрах команды
.RE
.PP
\fI2\fR
.RS 4
есть одна или более записей с недопустимыми паролями
.RE
.PP
\fI3\fR
.RS 4
не удалось открыть файл паролей
.RE
.PP
\fI4\fR
.RS 4
не удалось заблокировать файл паролей
.RE
.PP
\fI5\fR
.RS 4
не удалось изменить файл паролей
.RE
.PP
\fI6\fR
.RS 4
can\'t sort password files
.RE
