#!/bin/sh -e
# $Id: postinst,v 1.1.1.1 2010/04/15 06:46:10 kent Exp $

update-alternatives --install /usr/bin/ftp ftp /usr/bin/netkit-ftp 100 \
		    --slave /usr/share/man/man1/ftp.1.gz ftp.1.gz \
		    	    /usr/share/man/man1/netkit-ftp.1.gz

#DEBHELPER#
