#line 2 "client6_token.c"

#line 4 "client6_token.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer client6_create_buffer
#define yy_delete_buffer client6_delete_buffer
#define yy_flex_debug client6_flex_debug
#define yy_init_buffer client6_init_buffer
#define yy_flush_buffer client6_flush_buffer
#define yy_load_buffer_state client6_load_buffer_state
#define yy_switch_to_buffer client6_switch_to_buffer
#define yyin client6in
#define yyleng client6leng
#define yylex client6lex
#define yylineno client6lineno
#define yyout client6out
#define yyrestart client6restart
#define yytext client6text
#define yywrap client6wrap
#define yyalloc client6alloc
#define yyrealloc client6realloc
#define yyfree client6free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE client6restart(client6in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t client6leng;

extern FILE *client6in, *client6out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up client6text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up client6text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via client6restart()), so that the user can continue scanning by
	 * just pointing client6in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when client6text is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t client6leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow client6wrap()'s to do buffer switches
 * instead of setting up a fresh client6in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void client6restart (FILE *input_file  );
void client6_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE client6_create_buffer (FILE *file,int size  );
void client6_delete_buffer (YY_BUFFER_STATE b  );
void client6_flush_buffer (YY_BUFFER_STATE b  );
void client6push_buffer_state (YY_BUFFER_STATE new_buffer  );
void client6pop_buffer_state (void );

static void client6ensure_buffer_stack (void );
static void client6_load_buffer_state (void );
static void client6_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER client6_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE client6_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE client6_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE client6_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *client6alloc (yy_size_t  );
void *client6realloc (void *,yy_size_t  );
void client6free (void *  );

#define yy_new_buffer client6_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        client6ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            client6_create_buffer(client6in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        client6ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            client6_create_buffer(client6in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define client6wrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *client6in = (FILE *) 0, *client6out = (FILE *) 0;

typedef int yy_state_type;

extern int client6lineno;

int client6lineno = 1;

extern char *client6text;
#define yytext_ptr client6text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up client6text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	client6leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 34
#define YY_END_OF_BUFFER 35
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[308] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   35,   34,   24,   25,   26,   29,   33,   28,
       27,   30,   31,   32,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,    2,    2,   27,   33,   33,   24,
       26,   33,   27,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,    2,    2,   27,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   27,   33,
        5,    5,   33,   33,   33,    6,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   13,   33,   33,   27,

       33,   33,    5,   33,    5,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,    5,    5,    5,   33,   33,   33,   33,   33,
       33,   33,   14,   33,    4,   33,   33,   33,   33,   33,
       33,   33,   33,    5,    3,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   12,   33,   33,   33,
       33,   33,   33,   33,   23,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,    1,   33,   33,   33,   33,   33,   33,   33,   33,
        5,   33,   33,   33,   33,   33,   33,   33,   33,   33,

       33,    9,   33,   33,    5,   33,   33,   33,   33,   33,
       33,   33,   33,   10,   33,   33,    5,   33,   33,   33,
       33,   33,   33,   33,   15,   22,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
        7,   33,   33,   33,   19,   33,    8,   33,   33,   33,
       33,   33,   16,   33,   33,   18,   33,   33,   33,   17,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,   11,   33,   33,   33,   33,

       33,   33,   33,   33,   20,   21,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    6,    7,    8,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,   10,   11,    1,
        1,    1,    1,    1,   12,   12,   12,   12,   12,   12,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
        1,    1,    1,    1,   13,    1,   14,   15,   16,   17,

       18,   19,   20,   21,   22,   13,   13,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   13,   37,    1,   38,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[39] =
    {   0,
        1,    1,    2,    1,    1,    3,    3,    1,    3,    3,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    1,    1
    } ;

static yyconst flex_int16_t yy_base[313] =
    {   0,
        0,   38,   63,    0,   96,  134,  164,    0,    0,    0,
        0,    0,  401,  402,  398,  402,    0,  402,    0,  402,
      390,  402,  402,  402,  381,    0,    0,  383,  369,  366,
        1,  376,  375,  378,    0,  382,  175,  380,  380,  386,
        0,    0,  378,  369,  366,  360,  361,    1,  347,  350,
      362,  352,    2,  353,  353,  353,    0,  366,  186,  197,
      365,  363,  343,  357,  356,  352,    2,  350,  345,  344,
      346,  342,  341,  344,  329,  343,  332,  336,  208,  348,
      221,    3,  338,  323,  332,    0,  328,  323,  322,  326,
      323,   11,  331,  322,  312,  327,    0,  338,  326,   12,

      332,  332,  232,  330,   27,  309,  315,  312,  314,  311,
      315,  301,  307,  302,  295,  323,  311,  321,  296,  311,
      318,   41,  243,  316,  312,  291,  289,  313,  287,  303,
      302,  291,    0,  308,  307,  296,  305,  279,  278,  291,
      284,  297,   44,  295,    0,  298,   27,  267,  271,  285,
      294,  276,  281,  271,  265,  273,    0,  277,  271,   47,
      285,  269,  276,  271,    0,  266,  269,  264,  263,  266,
      259,  260,  257,  251,  260,  269,   51,  252,  252,  261,
      248,    0,  248,  253,  247,  232,  230,  235,  227,  225,
      233,  227,  213,  211,  192,  194,  199,  192,  190,  177,

      179,    0,  166,  182,  177,  151,  169,  154,  163,  142,
      161,  146,  134,    0,  134,  132,    0,  133,  131,  139,
      133,  129,  126,  142,    0,    0,  133,  130,  135,  146,
      126,  126,  127,  117,  123,  132,  115,  118,  117,  118,
      107,  108,  111,   97,   94,  104,   89,   93,  105,   96,
        0,   99,  102,   89,    0,   96,    0,   92,   90,   86,
       83,   87,  106,   86,   80,    0,   84,   86,  100,    0,
       97,   77,   66,   62,   57,   68,   66,   65,   63,   62,
       50,   49,   45,   54,   54,   53,   56,   39,   38,   51,
       45,   44,   46,   57,   56,    0,   30,   28,   33,   23,

       20,   11,   13,    5,    0,    0,  402,  262,  265,  268,
        4,    3
    } ;

static yyconst flex_int16_t yy_def[313] =
    {   0,
      308,  308,    2,    3,  309,  309,    2,    7,    2,    2,
        2,    2,  307,  307,  307,  307,  310,  307,  311,  307,
      311,  307,  307,  307,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  312,  312,  311,  311,   37,  307,
      310,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  312,  312,   37,   37,
       59,   60,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,   59,   79,
       79,   81,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,

      311,  311,   81,   60,  103,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  103,  123,   60,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,

      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,

      311,  311,  311,  311,  311,  311,    0,  307,  307,  307,
      307,  307
    } ;

static yyconst flex_int16_t yy_nxt[441] =
    {   0,
       14,   15,   16,   17,   18,   57,   42,   20,   21,   42,
       22,  105,  307,   47,   52,  307,   73,   45,   53,   67,
       43,   60,  306,   87,   48,   46,   74,   88,  114,   75,
      305,   68,  115,   42,  304,  124,   23,   24,   14,   15,
       16,   17,   18,  303,  302,   20,   21,  142,   22,  143,
      142,  163,  161,  176,  301,  177,  164,  176,  300,  192,
      299,  298,  297,  296,  295,  294,  293,  292,  291,  290,
      289,  288,  287,  286,   23,   24,   25,  285,  284,   26,
      283,  282,  281,  280,   27,  279,   28,  278,   29,   30,
      277,   31,   32,   33,  276,   34,   14,   15,   16,   17,

       18,  275,  274,   20,   36,  273,   22,  272,  271,  270,
      269,  268,  267,  266,  265,  264,  263,  262,  261,  260,
      259,  258,  257,  256,  255,  254,  253,  252,  251,  250,
      249,  248,   23,   24,   14,   15,   16,   17,   18,  247,
      246,   20,   36,  245,   22,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  234,  233,  232,  231,  230,
      229,  228,  227,  226,  225,  224,  223,  222,  221,  220,
       23,   24,   37,   38,  219,   39,  218,   39,   39,   39,
       39,   39,   39,   59,   60,  217,   61,  216,   61,   61,
       61,   61,   61,   61,   79,  215,  214,   80,  213,   80,

       80,   80,   80,   80,   80,   81,   62,  212,   82,  211,
       82,   82,   82,   82,   82,   82,  100,  210,  209,  101,
      208,  101,  101,  101,  101,  101,  101,  102,  207,  103,
      104,  206,  105,  176,  105,  105,  105,  105,  105,  105,
      123,  205,  204,  124,  203,  124,  124,  124,  124,  124,
      124,  144,  202,  201,  144,  200,  144,  144,  144,  144,
      144,  144,   19,   19,   19,   35,   35,   35,   41,  199,
       41,  198,  197,  196,  195,  194,  193,  191,  190,  189,
      188,  187,  186,  185,  184,  183,  182,  181,  180,  179,
      178,  142,  175,  174,  173,  172,  171,  170,  169,  168,

      167,  166,  165,  162,  104,  160,  159,  158,  157,  156,
      155,  154,  153,  152,  151,  150,  149,  148,  147,  146,
      145,   42,   42,  141,  140,  139,  138,  137,  136,  135,
      134,  133,  132,  131,  130,  129,  128,  127,  126,  125,
      122,   60,  121,  120,  119,  118,  117,  116,  113,  112,
      111,  110,  109,  108,  107,  106,  101,   99,   98,   97,
       96,   95,   94,   93,   92,   91,   90,   89,   86,   85,
       84,   83,   42,   80,   58,   78,   77,   76,   72,   71,
       70,   69,   66,   65,   64,   63,   43,   40,   61,   62,
       58,   56,   55,   54,   51,   50,   49,   44,   43,   40,

      307,   13,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307
    } ;

static yyconst flex_int16_t yy_chk[441] =
    {   0,
        1,    1,    1,    1,    1,  312,  311,    1,    1,   82,
        1,   82,    0,   27,   31,    0,   53,   26,   31,   48,
      100,  100,  304,   67,   27,   26,   53,   67,   92,   53,
      303,   48,   92,  105,  302,  105,    1,    1,    2,    2,
        2,    2,    2,  301,  300,    2,    2,  122,    2,  122,
      143,  147,  143,  160,  299,  160,  147,  177,  298,  177,
      297,  295,  294,  293,  292,  291,  290,  289,  288,  287,
      286,  285,  284,  283,    2,    2,    3,  282,  281,    3,
      280,  279,  278,  277,    3,  276,    3,  275,    3,    3,
      274,    3,    3,    3,  273,    3,    5,    5,    5,    5,

        5,  272,  271,    5,    5,  269,    5,  268,  267,  265,
      264,  263,  262,  261,  260,  259,  258,  256,  254,  253,
      252,  250,  249,  248,  247,  246,  245,  244,  243,  242,
      241,  240,    5,    5,    6,    6,    6,    6,    6,  239,
      238,    6,    6,  237,    6,  236,  235,  234,  233,  232,
      231,  230,  229,  228,  227,  224,  223,  222,  221,  220,
      219,  218,  216,  215,  213,  212,  211,  210,  209,  208,
        6,    6,    7,    7,  207,    7,  206,    7,    7,    7,
        7,    7,    7,   37,   37,  205,   37,  204,   37,   37,
       37,   37,   37,   37,   59,  203,  201,   59,  200,   59,

       59,   59,   59,   59,   59,   60,   60,  199,   60,  198,
       60,   60,   60,   60,   60,   60,   79,  197,  196,   79,
      195,   79,   79,   79,   79,   79,   79,   81,  194,   81,
       81,  193,   81,  192,   81,   81,   81,   81,   81,   81,
      103,  191,  190,  103,  189,  103,  103,  103,  103,  103,
      103,  123,  188,  187,  123,  186,  123,  123,  123,  123,
      123,  123,  308,  308,  308,  309,  309,  309,  310,  185,
      310,  184,  183,  181,  180,  179,  178,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  166,  164,  163,
      162,  161,  159,  158,  156,  155,  154,  153,  152,  151,

      150,  149,  148,  146,  144,  142,  141,  140,  139,  138,
      137,  136,  135,  134,  132,  131,  130,  129,  128,  127,
      126,  125,  124,  121,  120,  119,  118,  117,  116,  115,
      114,  113,  112,  111,  110,  109,  108,  107,  106,  104,
      102,  101,   99,   98,   96,   95,   94,   93,   91,   90,
       89,   88,   87,   85,   84,   83,   80,   78,   77,   76,
       75,   74,   73,   72,   71,   70,   69,   68,   66,   65,
       64,   63,   62,   61,   58,   56,   55,   54,   52,   51,
       50,   49,   47,   46,   45,   44,   43,   40,   39,   38,
       36,   34,   33,   32,   30,   29,   28,   25,   21,   15,

       13,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int client6_flex_debug;
int client6_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *client6text;
#line 1 "client6_token.l"
/* ported from KAME: cftoken.l,v 1.15 2002/09/24 14:20:49 itojun Exp */
/*
 * Copyright (C) 2002 WIDE Project.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the project nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
#line 36 "client6_token.l"
#include "config.h"

#include <stdarg.h>
#include <syslog.h>
#include <netinet/in.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>

#include "dhcp6.h"
#include "cfg.h"
#include "common.h"
#include "client6_parse.h"

const char *configfilename;
int lineno = 1;

static int cpyy_first_time = 1;
static int client6errorcount = 0;

#define YY_NO_UNPUT 1
#define ECHO if (fwrite(client6text, client6leng, 1, client6out) != 1) { \
                 YY_FATAL_ERROR("error performing ECHO on client6text"); \
             }

#ifndef NOCONFIG_DEBUG
#define YYDEBUG 1

int cfdebug = 1;
#else
int cfdebug = 0;
#endif

static void cfdebug_print __P((char *, char *, int));
extern int cf_post_config __P((void));

extern int client6parse(void);
extern int cf_post_config(void);

#define DP(str) if (cfdebug) cfdebug_print(str, client6text, client6leng)
#define DECHO if (cfdebug) cfdebug_print(NULL, client6text, client6leng);
/* abbreviations */





#line 757 "client6_token.c"

#define INITIAL 0
#define S_CNF 1
#define S_IFACE 2
#define S_ADDR 3
#define S_RNT 4
#define S_RBT 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int client6lex_destroy (void );

int client6get_debug (void );

void client6set_debug (int debug_flag  );

YY_EXTRA_TYPE client6get_extra (void );

void client6set_extra (YY_EXTRA_TYPE user_defined  );

FILE *client6get_in (void );

void client6set_in  (FILE * in_str  );

FILE *client6get_out (void );

void client6set_out  (FILE * out_str  );

yy_size_t client6get_leng (void );

char *client6get_text (void );

int client6get_lineno (void );

void client6set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int client6wrap (void );
#else
extern int client6wrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( client6text, client6leng, 1, client6out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( client6in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( client6in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, client6in))==0 && ferror(client6in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(client6in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int client6lex (void);

#define YY_DECL int client6lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after client6text and client6leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! client6in )
			client6in = stdin;

		if ( ! client6out )
			client6out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			client6ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				client6_create_buffer(client6in,YY_BUF_SIZE );
		}

		client6_load_buffer_state( );
		}

	{
#line 109 "client6_token.l"


	if (cpyy_first_time) {
		BEGIN S_CNF;
		cpyy_first_time = 0;
	}

	/* interface configuration */
#line 983 "client6_token.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of client6text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 308 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 402 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 117 "client6_token.l"
{ DECHO; BEGIN S_IFACE; return (INTERFACE); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 118 "client6_token.l"
{
	DECHO;
	client6lval.str = strdup(client6text);
	BEGIN S_CNF;
	return (IFNAME);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 125 "client6_token.l"
{ DECHO; BEGIN S_ADDR; return (ADDRESS); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 127 "client6_token.l"
{ DECHO; BEGIN S_ADDR; return (PREFIX); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 128 "client6_token.l"
{
	struct in6_addr addr;
	DECHO;
	if (inet_pton(AF_INET6, client6text, &addr) < 1) {
		dhcpv6_dprintf(LOG_ERR, "invalid address in line %d", lineno);
		return (-1);
	}
	client6lval.addr = addr;
	BEGIN S_CNF;
	return (IPV6ADDR);
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 139 "client6_token.l"
{ DECHO; return (IAID); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 140 "client6_token.l"
{ DECHO; return (V_TIME); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 141 "client6_token.l"
{ DECHO; return (P_TIME); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 142 "client6_token.l"
{ DECHO; return (RENEW_TIME); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 143 "client6_token.l"
{ DECHO; return (REBIND_TIME); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 144 "client6_token.l"
{ DECHO; return (PREFIX_DELEGATION_INTERFACE); }
	YY_BREAK
/* request */
case 12:
YY_RULE_SETUP
#line 146 "client6_token.l"
{ DECHO; return (REQUEST); }
	YY_BREAK
/* send */
case 13:
YY_RULE_SETUP
#line 149 "client6_token.l"
{ DECHO; return (SEND); }
	YY_BREAK
/* DHCP options */
case 14:
YY_RULE_SETUP
#line 151 "client6_token.l"
{ DECHO; return (OPTION); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 153 "client6_token.l"
{ DECHO; return (RAPID_COMMIT); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 154 "client6_token.l"
{ DECHO; return (PREFIX_DELEGATION); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 155 "client6_token.l"
{ DECHO; return (DNS_SERVERS); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 156 "client6_token.l"
{ DECHO; return (DOMAIN_LIST); }
	YY_BREAK
/* generic options */
case 19:
YY_RULE_SETUP
#line 158 "client6_token.l"
{ DECHO; return (INFO_ONLY); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 159 "client6_token.l"
{ DECHO; return (DEFAULT_IRT); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 160 "client6_token.l"
{ DECHO; return (MAXIMUM_IRT); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 161 "client6_token.l"
{ DECHO; return (TEMP_ADDR); }
	YY_BREAK
/* duration */
case 23:
YY_RULE_SETUP
#line 163 "client6_token.l"
{ DECHO; return (INFINITY); }
	YY_BREAK
/* misc */
case 24:
YY_RULE_SETUP
#line 166 "client6_token.l"
{ ; }
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 167 "client6_token.l"
{ lineno++; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 168 "client6_token.l"
{ DP("comment"); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 169 "client6_token.l"
{
	DECHO;
	client6lval.num = strtoll(client6text, NULL, 10);
	return (NUMBER);
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 174 "client6_token.l"
{ DECHO; return (SLASH); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 175 "client6_token.l"
{ DECHO; return (COMMA); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 176 "client6_token.l"
{ DP("end of sentence"); return (EOS); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 177 "client6_token.l"
{ DP("begin of closure"); return (BCL); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 178 "client6_token.l"
{ DP("end of closure"); return (ECL); }
	YY_BREAK
/* generic string */
case 33:
YY_RULE_SETUP
#line 181 "client6_token.l"
{
		DECHO;
		client6lval.str = strdup(client6text);
		return (STRING);
	}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 187 "client6_token.l"
ECHO;
	YY_BREAK
#line 1241 "client6_token.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(S_CNF):
case YY_STATE_EOF(S_IFACE):
case YY_STATE_EOF(S_ADDR):
case YY_STATE_EOF(S_RNT):
case YY_STATE_EOF(S_RBT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed client6in at a new source and called
			 * client6lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = client6in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( client6wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * client6text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of client6lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					client6realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			client6restart(client6in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) client6realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 308 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 308 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 307);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					client6restart(client6in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( client6wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve client6text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void client6restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        client6ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            client6_create_buffer(client6in,YY_BUF_SIZE );
	}

	client6_init_buffer(YY_CURRENT_BUFFER,input_file );
	client6_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void client6_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		client6pop_buffer_state();
	 *		client6push_buffer_state(new_buffer);
     */
	client6ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	client6_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (client6wrap()) processing, but the only time this flag
	 * is looked at is after client6wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void client6_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	client6in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE client6_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) client6alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in client6_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) client6alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in client6_create_buffer()" );

	b->yy_is_our_buffer = 1;

	client6_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with client6_create_buffer()
 * 
 */
    void client6_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		client6free((void *) b->yy_ch_buf  );

	client6free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a client6restart() or at EOF.
 */
    static void client6_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	client6_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then client6_init_buffer was _probably_
     * called from client6restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void client6_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		client6_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void client6push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	client6ensure_buffer_stack();

	/* This block is copied from client6_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from client6_switch_to_buffer. */
	client6_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void client6pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	client6_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		client6_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void client6ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)client6alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in client6ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)client6realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in client6ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE client6_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) client6alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in client6_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	client6_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to client6lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       client6_scan_bytes() instead.
 */
YY_BUFFER_STATE client6_scan_string (yyconst char * yystr )
{
    
	return client6_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to client6lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE client6_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) client6alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in client6_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = client6_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in client6_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up client6text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		client6text[client6leng] = (yy_hold_char); \
		(yy_c_buf_p) = client6text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		client6leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int client6get_lineno  (void)
{
        
    return client6lineno;
}

/** Get the input stream.
 * 
 */
FILE *client6get_in  (void)
{
        return client6in;
}

/** Get the output stream.
 * 
 */
FILE *client6get_out  (void)
{
        return client6out;
}

/** Get the length of the current token.
 * 
 */
yy_size_t client6get_leng  (void)
{
        return client6leng;
}

/** Get the current token.
 * 
 */

char *client6get_text  (void)
{
        return client6text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void client6set_lineno (int  line_number )
{
    
    client6lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see client6_switch_to_buffer
 */
void client6set_in (FILE *  in_str )
{
        client6in = in_str ;
}

void client6set_out (FILE *  out_str )
{
        client6out = out_str ;
}

int client6get_debug  (void)
{
        return client6_flex_debug;
}

void client6set_debug (int  bdebug )
{
        client6_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from client6lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    client6in = stdin;
    client6out = stdout;
#else
    client6in = (FILE *) 0;
    client6out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * client6lex_init()
     */
    return 0;
}

/* client6lex_destroy is for both reentrant and non-reentrant scanners. */
int client6lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		client6_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		client6pop_buffer_state();
	}

	/* Destroy the stack itself. */
	client6free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * client6lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *client6alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *client6realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void client6free (void * ptr )
{
	free( (char *) ptr );	/* see client6realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 186 "client6_token.l"


static void
cfdebug_print(w, t, l)
	char *w, *t;
	int l;
{
	if (w)
		dhcpv6_dprintf(LOG_DEBUG, "<%d>%s [%s] (%d)", yy_start, w, t, l);
	else
		dhcpv6_dprintf(LOG_DEBUG, "<%d>[%s] (%d)", yy_start, t, l);
}

static void
client6error0(int level, char *s, va_list ap)
{
	char ebuf[BUFSIZ], *bp, *ep;

	bp = ebuf;
	ep = ebuf + sizeof(ebuf);
	bp += snprintf(bp, ep - bp, "%s %d: ", configfilename, lineno);
	if (bp < ep)
		bp += vsnprintf(bp, ep - bp, s, ap);

	dhcpv6_dprintf(level, ebuf);
}

void
client6error(char *s, ...)
{
	va_list ap;
	va_start(ap, s);
	client6error0(LOG_ERR, s, ap);
	va_end(ap);
	client6errorcount++;
}

void
cpyywarn(char *s, ...)
{
	va_list ap;
	va_start(ap, s);
	client6error0(LOG_WARNING, s, ap);
	va_end(ap);
}

int
cfparse(const char *conf)
{
	configfilename = conf;
	if ((client6in = fopen(configfilename, "r")) == NULL) {
		if (errno == ENOENT)
			return (0);
		dhcpv6_dprintf(LOG_ERR, "cfparse: fopen(%s): %s",
			configfilename, strerror(errno));
		return (-1);
	}

	if (client6parse() || client6errorcount) {
		if (client6errorcount) {
			client6error("fatal parse failure: exiting (%d errors)",
				client6errorcount);
		} else
			client6error("fatal parse failure: exiting");
		return (-1);
	}

	return (cf_post_config());
}

