#line 2 "server6_token.c"

#line 4 "server6_token.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer server6_create_buffer
#define yy_delete_buffer server6_delete_buffer
#define yy_flex_debug server6_flex_debug
#define yy_init_buffer server6_init_buffer
#define yy_flush_buffer server6_flush_buffer
#define yy_load_buffer_state server6_load_buffer_state
#define yy_switch_to_buffer server6_switch_to_buffer
#define yyin server6in
#define yyleng server6leng
#define yylex server6lex
#define yylineno server6lineno
#define yyout server6out
#define yyrestart server6restart
#define yytext server6text
#define yywrap server6wrap
#define yyalloc server6alloc
#define yyrealloc server6realloc
#define yyfree server6free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE server6restart(server6in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t server6leng;

extern FILE *server6in, *server6out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up server6text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up server6text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via server6restart()), so that the user can continue scanning by
	 * just pointing server6in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when server6text is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t server6leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow server6wrap()'s to do buffer switches
 * instead of setting up a fresh server6in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void server6restart (FILE *input_file  );
void server6_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE server6_create_buffer (FILE *file,int size  );
void server6_delete_buffer (YY_BUFFER_STATE b  );
void server6_flush_buffer (YY_BUFFER_STATE b  );
void server6push_buffer_state (YY_BUFFER_STATE new_buffer  );
void server6pop_buffer_state (void );

static void server6ensure_buffer_stack (void );
static void server6_load_buffer_state (void );
static void server6_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER server6_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE server6_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE server6_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE server6_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *server6alloc (yy_size_t  );
void *server6realloc (void *,yy_size_t  );
void server6free (void *  );

#define yy_new_buffer server6_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        server6ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            server6_create_buffer(server6in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        server6ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            server6_create_buffer(server6in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define server6wrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *server6in = (FILE *) 0, *server6out = (FILE *) 0;

typedef int yy_state_type;

extern int server6lineno;

int server6lineno = 1;

extern char *server6text;
#define yytext_ptr server6text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up server6text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	server6leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 41
#define YY_END_OF_BUFFER 42
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[458] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   42,   40,
       33,   32,   40,   38,   38,   39,   35,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,   35,   38,
       38,   38,   38,   38,   38,   38,   38,   33,    0,   31,
       38,   36,   38,   35,   34,   38,   34,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   29,   38,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,   12,   12,   12,   38,
       38,   38,   38,   38,   37,   35,   38,   34,   34,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,   34,   38,   38,   38,   38,   38,   35,   38,
       38,   34,   34,   34,   38,   38,   11,   38,    6,    9,
       38,   38,    4,   38,    7,   38,   38,   38,   38,   38,
       16,   38,   38,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,   34,   34,
       38,   38,   38,   38,   38,   35,   38,   34,   34,   34,
       38,   15,    1,   38,   38,   38,   38,   38,   38,    8,
       38,    5,   38,   38,   38,    3,    3,    3,    3,    3,
        3,    3,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,   12,   12,   38,   38,   38,
       38,   38,   38,   38,   34,   38,   38,   38,   38,   17,
       38,   13,   38,   38,   38,   38,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

       34,   38,   38,   38,   38,   38,   38,   38,   14,   38,
       38,   38,   38,   38,   38,   38,   38,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,   38,   38,
       38,   38,   18,   38,   38,   10,   30,   38,   38,   38,
       38,   38,   38,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,   38,   38,   38,   38,   34,   38,    2,
       38,   38,   38,   38,   38,    3,    3,    2,    3,    3,
        3,    3,    3,   38,   38,   38,   38,   34,   38,   38,
       24,   38,   38,    3,    3,    3,    3,    3,    3,   38,
       38,   38,   38,   34,   38,   25,   38,   38,    3,    3,

        3,    3,    3,   23,   38,   38,   38,   38,   38,   38,
        3,    3,    3,   38,   19,   20,   38,   38,   38,    3,
        3,    3,   38,   38,   38,   38,   38,    3,    3,    3,
       38,   38,   38,   38,   26,    3,    3,    3,   38,   38,
       27,   38,    3,    3,   21,   38,   28,    3,   38,   38,
       38,   38,   38,   38,   38,   22,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    6,    7,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    9,   10,    1,
        1,    1,    1,    1,   11,   11,   11,   11,   11,   11,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
        1,    1,    1,    1,   13,    1,   14,   15,   16,   17,

       18,   19,   20,   21,   22,   12,   23,   24,   25,   26,
       27,   28,   12,   29,   30,   31,   32,   33,   34,   35,
       36,   12,   37,    1,   38,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[39] =
    {   0,
        1,    1,    1,    1,    2,    2,    1,    2,    2,    1,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    1,    1
    } ;

static yyconst flex_int16_t yy_base[461] =
    {   0,
        0,    0,   38,    0,   69,    0,   72,   76,  699,  700,
      696,  700,  694,  688,    0,  700,  103,  686,   73,   89,
       84,  665,  666,  101,  670,  663,   73,   64,  672,  662,
      674,  679,    0,  122,  677,  117,  118,  126,  656,  657,
      129,  661,  654,  117,  131,  663,  653,  665,  151,  142,
      155,  145,  148,  138,  157,  155,  652,  675,  673,  700,
        0,  667,  666,  175,  187,  170,  664,  191,  648,  649,
      643,  639,  646,  169,  641,  635,  638,  646,  637,  192,
       70,    0,  638,    0,  653,  652,  211,  223,  179,  650,
      203,  634,  635,  629,  625,  632,  193,  627,  621,  624,

      632,  623,  220,  131,    0,  624,  638,  239,  243,  616,
      202,  187,  620,  622,  635,  253,  247,  267,  248,  251,
      615,  624,  608,  608,  621,  615,  618,  612,  612,  609,
      613,  611,  608,  615,  610,  610,  593,  603,  616,  279,
      257,  293,  271,  297,  596,  605,  589,  589,  602,  596,
      599,  593,  593,  590,  594,  592,  589,  596,  591,  591,
      574,  584,  319,  592,  291,  582,  575,  586,  283,  592,
      592,  331,  590,  308,  580,  563,    0,  568,    0,  573,
      568,  564,    0,  565,    0,  192,  573,  564,  553,  554,
        0,  569,  569,  311,  576,  576,  343,  574,  315,  564,

      547,    0,  552,    0,  557,  552,  548,    0,  549,    0,
      240,  557,  548,  537,  538,    0,  553,  553,  355,  316,
      539,  539,  550,  561,  551,  323,  335,  367,  558,  554,
      532,    0,    0,  535,  538,  540,  532,  528,  521,    0,
      538,    0,  549,  524,  547,  347,  359,  379,  545,  541,
      519,    0,    0,  522,  525,  527,  519,  515,  508,    0,
      525,    0,  536,  511,  534,  529,  371,  519,  511,  530,
      520,  503,  524,  383,  522,  500,  510,  497,  513,    0,
      521,    0,  520,  493,  518,  498,  513,  393,  511,  489,
      499,  486,  502,    0,  510,    0,  509,  482,  507,  487,

      501,  480,  494,  491,  489,  474,  394,  498,    0,  476,
      466,  485,  476,  468,  476,  469,  474,  397,  489,    0,
      467,  457,  476,  467,  459,  467,  460,  465,  453,  454,
      457,  466,    0,  474,  398,    0,    0,  463,  458,  457,
      453,  448,  457,  467,  401,    0,    0,  456,  451,  450,
      446,  441,  450,  450,  445,  441,  436,  456,  457,    0,
      443,  436,  442,  441,  440,  449,  450,    0,  436,  429,
      435,  434,  433,  421,  422,  423,  429,  438,  427,  426,
        0,  424,  437,  433,  422,  421,    0,  419,  432,  406,
      409,  412,  403,    0,  427,    0,  413,  399,    0,  424,

        0,  410,  396,    0,  421,  394,  394,  392,  393,  399,
      389,  390,  396,  381,    0,    0,  395,  398,  390,  392,
      395,  367,  362,  358,  343,  338,  338,  327,  318,  322,
      308,  309,  307,  299,    0,  288,  284,    0,  252,  245,
        0,  248,    0,  232,    0,  225,    0,    0,  206,  202,
      212,  153,  159,  122,  111,    0,  700,  410,  108,   89
    } ;

static yyconst flex_int16_t yy_def[461] =
    {   0,
      457,    1,  457,    3,    1,    5,    1,    1,  457,  457,
      457,  457,  458,  459,  459,  457,  459,  459,   17,   17,
       17,  459,  459,  459,  459,  459,  459,  459,  459,  459,
      459,  460,  460,  460,  460,   34,   34,   34,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,   17,   49,
       49,   49,   17,  459,  459,  459,  459,  457,  458,  457,
      459,  459,  459,   17,  459,   64,   65,   64,  459,  459,
      459,  459,  459,  459,  459,  459,  459,  459,  459,  459,
      459,  459,  459,  460,  460,  460,   34,  460,   87,   88,
       87,  460,  460,  460,  460,  460,  460,  460,  460,  460,

      460,  460,  460,  460,  460,  460,   64,   64,   64,  459,
      459,  459,  459,  459,  459,   64,  116,  116,  118,  116,
      459,  459,  459,  459,  459,  459,  459,  459,  459,  459,
      459,  459,  459,  459,  459,  459,  459,  459,  460,   87,
      140,  140,  142,  140,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,   65,  459,  459,  459,  459,  459,  459,  459,
      459,  118,   65,  172,  459,  459,  459,  459,  459,  459,
      459,  459,  459,  459,  459,  459,  459,  459,  459,  459,
      459,  459,  459,  460,  460,  460,  142,   88,  197,  460,

      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  172,  219,
      459,  459,  459,  459,  459,  459,  459,  219,  228,   65,
      459,  459,  459,  459,  459,  459,  459,  459,  459,  459,
      459,  459,  459,  459,  459,  460,  460,  197,  248,   88,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  172,  172,  459,  459,  459,
      459,  459,  459,  459,  459,  459,  459,  459,  459,  459,
      459,  459,  459,  459,  459,  459,  460,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,

      163,  459,  459,  459,  459,  459,  459,  459,  459,  459,
      459,  459,  459,  459,  459,  459,  459,  460,  460,  460,
      460,  460,  460,  460,  460,  460,  460,  460,  459,  459,
      459,  459,  459,  459,  459,  459,  459,  459,  459,  459,
      459,  459,  459,  460,  460,  460,  460,  460,  460,  460,
      460,  460,  460,  459,  459,  459,  459,  459,  459,  459,
      459,  459,  459,  459,  459,  460,  460,  460,  460,  460,
      460,  460,  460,  459,  459,  459,  459,  459,  459,  459,
      459,  459,  459,  460,  460,  460,  460,  460,  460,  459,
      459,  459,  459,  459,  459,  459,  459,  459,  460,  460,

      460,  460,  460,  459,  459,  459,  459,  459,  459,  459,
      460,  460,  460,  459,  459,  459,  459,  459,  459,  460,
      460,  460,  459,  459,  459,  459,  459,  460,  460,  460,
      459,  459,  459,  459,  459,  460,  460,  460,  459,  459,
      459,  459,  460,  460,  459,  459,  459,  460,  459,  459,
      459,  459,  459,  459,  459,  459,    0,  457,  457,  457
    } ;

static yyconst flex_int16_t yy_nxt[739] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   16,
       19,   15,   15,   20,   19,   19,   21,   19,   19,   22,
       23,   24,   15,   25,   15,   15,   26,   27,   28,   29,
       30,   15,   31,   15,   15,   15,   16,   16,   10,   11,
       12,   13,   32,   33,   16,   34,   35,   16,   36,   33,
       33,   37,   36,   36,   38,   36,   36,   39,   40,   41,
       33,   42,   33,   33,   43,   44,   45,   46,   47,   33,
       48,   33,   33,   33,   16,   16,   49,   79,   61,   50,
       66,   80,   51,   50,   50,   52,   50,   50,   53,   61,
       84,   66,   53,   54,   61,  136,   66,   54,  137,   77,

       55,   78,   56,   57,   55,   68,   56,   57,   63,   61,
       64,   65,   69,   66,   73,   70,   66,   66,   66,   66,
       66,   66,   84,   84,   89,   89,   74,   86,  456,   87,
       88,   84,   89,   89,   91,   89,   89,   89,   89,   89,
       89,   92,   96,  100,  102,  101,  455,   61,  103,  108,
       61,   73,  108,   61,   97,   66,  160,   93,  107,  161,
       61,  108,  108,  111,  108,  108,  108,  108,  108,  108,
      112,  109,  113,  110,   80,   61,   70,  117,   69,   70,
      454,   82,  116,  453,   84,  117,  141,  126,  117,  117,
      117,  117,  117,  117,  118,   67,   61,  119,  117,  127,

      119,  119,  119,  119,  119,  119,  133,  120,   84,  238,
      141,  150,  132,  239,  166,  134,  452,  135,  140,  144,
      165,  141,  451,  151,  141,  141,  141,  141,  141,  141,
      142,   90,  127,  143,  157,  450,  143,  143,  143,  143,
      143,  143,  449,  158,   61,  159,  117,  163,   61,  448,
      117,  163,   61,   61,  170,  174,   61,  258,  170,  120,
      169,  259,   84,  170,  195,  447,  170,  170,  170,  170,
      170,  170,  171,  446,  172,  173,   84,  174,  199,  175,
      174,  174,  174,  174,  174,  174,  194,  445,   63,  195,
      226,   65,  195,  195,  195,  195,  195,  195,  196,  444,

      197,  198,   84,  199,  195,  443,  199,  199,  199,  199,
      199,  199,  181,   61,  442,  229,   86,  222,  246,   88,
       84,   61,  249,  267,  441,  200,  219,  440,   63,  220,
      226,  439,  220,  220,  220,  220,  220,  220,  228,  438,
      273,  229,  274,  437,  229,  229,  229,  229,  229,  229,
      248,  436,   86,  249,  246,  435,  249,  249,  249,  249,
      249,  249,  266,  434,  287,  267,  288,  433,  267,  267,
      267,  267,  267,  267,  275,  432,   61,  275,  229,  301,
      275,  275,  275,  275,  275,  275,  289,  431,  273,  289,
      308,  430,  289,  289,  289,  289,  289,  289,  287,  334,

      319,  335,  344,  334,  345,  359,  344,  423,  367,  424,
       59,   59,  429,  428,  427,  426,  425,  422,  421,  420,
      419,  418,  417,  416,  415,  414,  413,  412,  411,  410,
      409,  408,  407,  406,  405,  404,  403,  402,  401,  400,
      399,  398,  397,  396,  395,  394,  393,  392,  391,  390,
      389,  388,  387,  386,  385,  344,  384,  383,  382,  381,
      380,  379,  334,  378,  377,  376,  375,  374,  373,  372,
      371,  370,  369,  368,  366,  365,  364,  363,  362,  361,
      360,  358,  357,  356,  355,  354,  353,  352,  351,  350,
      349,  348,  347,  346,  287,  343,  342,  341,  340,  339,

      338,  337,  336,  273,  333,  332,  331,  330,  329,  230,
      328,  327,  326,  325,  324,  323,  322,  321,  320,  198,
      318,  317,  316,  315,  314,  313,  312,  311,  310,  309,
      173,  307,  306,  305,  304,  303,  302,  301,  300,  299,
      298,  297,  296,  295,  294,  293,  292,  291,  290,   84,
       84,  286,  285,  284,  283,  282,  281,  280,  279,  278,
      277,  276,   61,   61,  272,  271,  270,  269,  268,  265,
      264,  263,  262,  261,  260,  257,  256,  255,  254,  253,
      252,  251,  250,  247,   88,  245,  244,  243,  242,  241,
      240,  237,  236,  235,  234,  233,  232,  231,  230,  227,

       65,  225,  224,  223,  221,  218,  217,  216,  215,  214,
      213,  212,  211,  210,  209,  208,  207,  206,  205,  204,
      203,  202,  201,  139,  193,  192,  191,  190,  189,  188,
      187,  186,  185,  184,  183,  182,  181,  180,  179,  178,
      177,  176,  115,  168,  167,  164,  163,  162,  156,  155,
      154,  153,  152,  149,  148,  147,  146,  145,   84,  139,
       85,  138,  132,  131,  130,  129,  128,  125,  124,  123,
      122,  121,   61,  115,   62,   60,   58,  114,  106,  105,
      104,   99,   98,   95,   94,   90,   85,   83,   82,   81,
       76,   75,   72,   71,   67,   62,   60,   58,  457,    9,

      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457
    } ;

static yyconst flex_int16_t yy_chk[739] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    5,   28,   19,    5,
       19,   28,    5,    5,    5,    5,    5,    5,    7,   21,
      460,   21,    8,    7,   20,   81,   20,    8,   81,   27,

        7,   27,    7,    7,    8,   20,    8,    8,   17,  459,
       17,   17,   20,   17,   24,   21,   17,   17,   17,   17,
       17,   17,   36,   37,   36,   37,   24,   34,  455,   34,
       34,   38,   34,   38,   37,   34,   34,   34,   34,   34,
       34,   37,   41,   44,   45,   44,  454,   50,   45,   50,
       52,   54,   52,   53,   41,   53,  104,   38,   49,  104,
       51,   49,   51,   54,   49,   49,   49,   49,   49,   49,
       55,   51,   56,   53,   55,   66,   52,   66,   51,   53,
      453,   56,   64,  452,   89,   64,   89,   74,   64,   64,
       64,   64,   64,   64,   65,   65,   68,   65,   68,   74,

       65,   65,   65,   65,   65,   65,   80,   68,   91,  186,
       91,   97,  112,  186,  112,   80,  451,   80,   87,   91,
      111,   87,  450,   97,   87,   87,   87,   87,   87,   87,
       88,   88,  111,   88,  103,  449,   88,   88,   88,   88,
       88,   88,  446,  103,  108,  103,  108,  108,  109,  444,
      109,  109,  117,  119,  117,  119,  120,  211,  120,  109,
      116,  211,  141,  116,  141,  442,  116,  116,  116,  116,
      116,  116,  118,  440,  118,  118,  143,  118,  143,  120,
      118,  118,  118,  118,  118,  118,  140,  439,  169,  140,
      169,  169,  140,  140,  140,  140,  140,  140,  142,  437,

      142,  142,  144,  142,  144,  436,  142,  142,  142,  142,
      142,  142,  165,  174,  434,  174,  194,  165,  194,  194,
      199,  220,  199,  220,  433,  144,  163,  432,  226,  163,
      226,  431,  163,  163,  163,  163,  163,  163,  172,  430,
      227,  172,  227,  429,  172,  172,  172,  172,  172,  172,
      197,  428,  246,  197,  246,  427,  197,  197,  197,  197,
      197,  197,  219,  426,  247,  219,  247,  425,  219,  219,
      219,  219,  219,  219,  228,  424,  267,  228,  267,  267,
      228,  228,  228,  228,  228,  228,  248,  423,  274,  248,
      274,  422,  248,  248,  248,  248,  248,  248,  288,  307,

      288,  307,  318,  335,  318,  335,  345,  414,  345,  414,
      458,  458,  421,  420,  419,  418,  417,  413,  412,  411,
      410,  409,  408,  407,  406,  405,  403,  402,  400,  398,
      397,  395,  393,  392,  391,  390,  389,  388,  386,  385,
      384,  383,  382,  380,  379,  378,  377,  376,  375,  374,
      373,  372,  371,  370,  369,  367,  366,  365,  364,  363,
      362,  361,  359,  358,  357,  356,  355,  354,  353,  352,
      351,  350,  349,  348,  344,  343,  342,  341,  340,  339,
      338,  334,  332,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  319,  317,  316,  315,  314,  313,

      312,  311,  310,  308,  306,  305,  304,  303,  302,  301,
      300,  299,  298,  297,  295,  293,  292,  291,  290,  289,
      287,  286,  285,  284,  283,  281,  279,  278,  277,  276,
      275,  273,  272,  271,  270,  269,  268,  266,  265,  264,
      263,  261,  259,  258,  257,  256,  255,  254,  251,  250,
      249,  245,  244,  243,  241,  239,  238,  237,  236,  235,
      234,  231,  230,  229,  225,  224,  223,  222,  221,  218,
      217,  215,  214,  213,  212,  209,  207,  206,  205,  203,
      201,  200,  198,  196,  195,  193,  192,  190,  189,  188,
      187,  184,  182,  181,  180,  178,  176,  175,  173,  171,

      170,  168,  167,  166,  164,  162,  161,  160,  159,  158,
      157,  156,  155,  154,  153,  152,  151,  150,  149,  148,
      147,  146,  145,  139,  138,  137,  136,  135,  134,  133,
      132,  131,  130,  129,  128,  127,  126,  125,  124,  123,
      122,  121,  115,  114,  113,  110,  107,  106,  102,  101,
      100,   99,   98,   96,   95,   94,   93,   92,   90,   86,
       85,   83,   79,   78,   77,   76,   75,   73,   72,   71,
       70,   69,   67,   63,   62,   59,   58,   57,   48,   47,
       46,   43,   42,   40,   39,   35,   32,   31,   30,   29,
       26,   25,   23,   22,   18,   14,   13,   11,    9,  457,

      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457,  457,  457,
      457,  457,  457,  457,  457,  457,  457,  457
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int server6_flex_debug;
int server6_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *server6text;
#line 1 "server6_token.l"
/*
 * Copyright (C) International Business Machines  Corp., 2003
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the project nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
/* Author: Shirley Ma, xma@us.ibm.com */
#line 36 "server6_token.l"
#include "config.h"

#include <stdarg.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <syslog.h>
#include <netinet/in.h>
#include <net/if.h>

#include "dhcp6.h"
#include "cfg.h"
#include "common.h"
#include "server6_conf.h"
#include "server6_parse.h"

#define YY_NO_UNPUT 1
#define ECHO if (fwrite(server6text, server6leng, 1, server6out) != 1) { \
                 YY_FATAL_ERROR("error performing ECHO on server6text"); \
             }

const char *configfilename;
int num_lines = 1;
int server6errorcount = 0;
extern int server6parse(void);
extern struct rootgroup *globalgroup;




#line 852 "server6_token.c"

#define INITIAL 0
#define S_IFACE 1
#define S_DUID 2
#define S_OPTION 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int server6lex_destroy (void );

int server6get_debug (void );

void server6set_debug (int debug_flag  );

YY_EXTRA_TYPE server6get_extra (void );

void server6set_extra (YY_EXTRA_TYPE user_defined  );

FILE *server6get_in (void );

void server6set_in  (FILE * in_str  );

FILE *server6get_out (void );

void server6set_out  (FILE * out_str  );

yy_size_t server6get_leng (void );

char *server6get_text (void );

int server6get_lineno (void );

void server6set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int server6wrap (void );
#else
extern int server6wrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( server6text, server6leng, 1, server6out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( server6in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( server6in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, server6in))==0 && ferror(server6in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(server6in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int server6lex (void);

#define YY_DECL int server6lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after server6text and server6leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! server6in )
			server6in = stdin;

		if ( ! server6out )
			server6out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			server6ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				server6_create_buffer(server6in,YY_BUF_SIZE );
		}

		server6_load_buffer_state( );
		}

	{
#line 85 "server6_token.l"


#line 1070 "server6_token.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of server6text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 458 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 700 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 87 "server6_token.l"
{ return GROUP; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 89 "server6_token.l"
{ BEGIN S_IFACE; return INTERFACE; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 90 "server6_token.l"
{ BEGIN INITIAL; server6lval.str = strdup(server6text); return IFNAME;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 92 "server6_token.l"
{ return LINK; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 93 "server6_token.l"
{ return RELAY; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 94 "server6_token.l"
{ return HOST; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 96 "server6_token.l"
{ return POOL; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 97 "server6_token.l"
{ return RANGE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 99 "server6_token.l"
{ return IAID; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 100 "server6_token.l"
{ return IAIDINFO; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 102 "server6_token.l"
{ BEGIN S_DUID; return DUID; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 103 "server6_token.l"
{ BEGIN INITIAL; server6lval.str = strdup(server6text); return DUID_ID; } 
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 105 "server6_token.l"
{ return PREFIX; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 106 "server6_token.l"
{ return ADDRESS;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 108 "server6_token.l"
{ BEGIN S_OPTION; return ALLOW; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 109 "server6_token.l"
{ BEGIN S_OPTION; return SEND; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 110 "server6_token.l"
{ BEGIN S_OPTION; return OPTION; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 112 "server6_token.l"
{ BEGIN INITIAL; return UNICAST; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 113 "server6_token.l"
{ BEGIN INITIAL; return RAPIDCOMMIT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 114 "server6_token.l"
{ BEGIN INITIAL; return TEMPIPV6ADDR; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 115 "server6_token.l"
{ BEGIN INITIAL; return INFO_ONLY; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 116 "server6_token.l"
{ BEGIN INITIAL; return INFO_REFRESH_TIME; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 117 "server6_token.l"
{ BEGIN INITIAL; return DNS_SERVERS;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 119 "server6_token.l"
{ return RENEWTIME; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 120 "server6_token.l"
{ return REBINDTIME; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 121 "server6_token.l"
{ return VALIDLIFETIME; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 122 "server6_token.l"
{ return PREFERLIFETIME; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 123 "server6_token.l"
{ return PREFERENCE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 125 "server6_token.l"
{ return TO; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 126 "server6_token.l"
{ return INFINITY; }
	YY_BREAK
case 31:
*yy_cp = (yy_hold_char); /* undo effects of setting up server6text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up server6text again */
YY_RULE_SETUP
#line 128 "server6_token.l"
{/* ignore comments */}
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 129 "server6_token.l"
{num_lines++;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 130 "server6_token.l"
{}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 131 "server6_token.l"
{
			struct in6_addr addr;
			int i;
				
			i = inet_pton(AF_INET6, server6text, &addr);
			if (i < 1) {
				dhcpv6_dprintf(LOG_ERR, "invalid address in line %d", num_lines); 
				return BAD_TOKEN;
			}

			server6lval.addr = addr;
			return IPV6ADDR;
		}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 145 "server6_token.l"
{ server6lval.num = strtoll(server6text, NULL, 10); return NUMBER; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 146 "server6_token.l"
{ server6lval.snum = strtoll(server6text, NULL, 10); return SIGNEDNUMBER; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 147 "server6_token.l"
{ server6lval.dec = atof(server6text); return DECIMAL; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 148 "server6_token.l"
{
			static char name[MAXDNAME];
			strncpy(name, server6text, MAXDNAME-1);
			name[MAXDNAME-1] = '\0';
			server6lval.str = name;
			return STRING;
		}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 155 "server6_token.l"
{ return *server6text; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 156 "server6_token.l"
{ return BAD_TOKEN; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 158 "server6_token.l"
ECHO;
	YY_BREAK
#line 1354 "server6_token.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(S_IFACE):
case YY_STATE_EOF(S_DUID):
case YY_STATE_EOF(S_OPTION):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed server6in at a new source and called
			 * server6lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = server6in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( server6wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * server6text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of server6lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					server6realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			server6restart(server6in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) server6realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 458 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 458 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 457);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					server6restart(server6in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( server6wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve server6text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void server6restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        server6ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            server6_create_buffer(server6in,YY_BUF_SIZE );
	}

	server6_init_buffer(YY_CURRENT_BUFFER,input_file );
	server6_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void server6_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		server6pop_buffer_state();
	 *		server6push_buffer_state(new_buffer);
     */
	server6ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	server6_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (server6wrap()) processing, but the only time this flag
	 * is looked at is after server6wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void server6_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	server6in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE server6_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) server6alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in server6_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) server6alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in server6_create_buffer()" );

	b->yy_is_our_buffer = 1;

	server6_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with server6_create_buffer()
 * 
 */
    void server6_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		server6free((void *) b->yy_ch_buf  );

	server6free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a server6restart() or at EOF.
 */
    static void server6_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	server6_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then server6_init_buffer was _probably_
     * called from server6restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void server6_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		server6_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void server6push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	server6ensure_buffer_stack();

	/* This block is copied from server6_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from server6_switch_to_buffer. */
	server6_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void server6pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	server6_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		server6_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void server6ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)server6alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in server6ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)server6realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in server6ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE server6_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) server6alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in server6_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	server6_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to server6lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       server6_scan_bytes() instead.
 */
YY_BUFFER_STATE server6_scan_string (yyconst char * yystr )
{
    
	return server6_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to server6lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE server6_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) server6alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in server6_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = server6_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in server6_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up server6text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		server6text[server6leng] = (yy_hold_char); \
		(yy_c_buf_p) = server6text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		server6leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int server6get_lineno  (void)
{
        
    return server6lineno;
}

/** Get the input stream.
 * 
 */
FILE *server6get_in  (void)
{
        return server6in;
}

/** Get the output stream.
 * 
 */
FILE *server6get_out  (void)
{
        return server6out;
}

/** Get the length of the current token.
 * 
 */
yy_size_t server6get_leng  (void)
{
        return server6leng;
}

/** Get the current token.
 * 
 */

char *server6get_text  (void)
{
        return server6text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void server6set_lineno (int  line_number )
{
    
    server6lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see server6_switch_to_buffer
 */
void server6set_in (FILE *  in_str )
{
        server6in = in_str ;
}

void server6set_out (FILE *  out_str )
{
        server6out = out_str ;
}

int server6get_debug  (void)
{
        return server6_flex_debug;
}

void server6set_debug (int  bdebug )
{
        server6_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from server6lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    server6in = stdin;
    server6out = stdout;
#else
    server6in = (FILE *) 0;
    server6out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * server6lex_init()
     */
    return 0;
}

/* server6lex_destroy is for both reentrant and non-reentrant scanners. */
int server6lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		server6_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		server6pop_buffer_state();
	}

	/* Destroy the stack itself. */
	server6free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * server6lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *server6alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *server6realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void server6free (void * ptr )
{
	free( (char *) ptr );	/* see server6realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 157 "server6_token.l"



static void
server6error0(int level, char *s, va_list ap)
{
	char ebuf[BUFSIZ], *bp, *ep;

	bp = ebuf;
	ep = ebuf + sizeof(ebuf);
	bp += snprintf(bp, ep - bp, "%s %d: ", configfilename, num_lines);
	if (bp < ep)
		bp += vsnprintf(bp, ep - bp, s, ap);

	dhcpv6_dprintf(level, ebuf);
}

void
server6error(char *s, ...)
{
	va_list ap;
	va_start(ap, s);
	server6error0(LOG_ERR, s, ap);
	va_end(ap);
	server6errorcount++;
}

int
sfparse(const char *conf)
{
	configfilename = conf;
	if ((server6in = fopen(configfilename, "r")) == NULL) {
		if (errno == ENOENT)
			return (0);
		dhcpv6_dprintf(LOG_ERR, "sfparse: fopen(%s): %s",
				configfilename, strerror(errno));
		return (-1);
	}

	if (server6parse() || server6errorcount) {
		if (server6errorcount) {
			server6error("fatal parse failure: exiting (%d errors)",
					server6errorcount);
		} else
			server6error("fatal parse failure: exiting");
		return (-1);
	}
	post_config(globalgroup);

	return (0);
}

