'\" t
.\"     Title: useradd
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.74.3 <http://docbook.sf.net/>
.\"      Date: 10/05/2009
.\"    Manual: Commandes de gestion du syst\(`eme
.\"    Source: Commandes de gestion du syst\(`eme
.\"  Language: French
.\"
.TH "USERADD" "8" "10/05/2009" "Commandes de gestion du syst\(`em" "Commandes de gestion du syst\(`em"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOM"
useradd \- cr\('eer un nouvel utilisateur ou modifier les informations par d\('efaut appliqu\('ees aux nouveaux utilisateurs
.SH "SYNOPSIS"
.HP \w'\fBuseradd\fR\ 'u
\fBuseradd\fR [\fIoptions\fR] \fILOGIN\fR
.HP \w'\fBuseradd\fR\ 'u
\fBuseradd\fR \-D
.HP \w'\fBuseradd\fR\ 'u
\fBuseradd\fR \-D [\fIoptions\fR]
.SH "DESCRIPTION"
.PP
When invoked without the
\fB\-D\fR
option, the
\fBuseradd\fR
command creates a new user account using the values specified on the command line plus the default values from the system\&. Depending on command line options, the
\fBuseradd\fR
command will update system files and may also create the new user\'s home directory and copy initial files\&.
.PP
By default, a group will also be created for the new user (see
\fB\-g\fR,
\fB\-N\fR,
\fB\-U\fR, and
\fBUSERGROUPS_ENAB\fR)\&.
.SH "OPTIONS"
.PP
Les options disponibles pour la commande
\fBuseradd\fR
sont\ \&:
.PP
\fB\-b\fR, \fB\-\-base\-dir\fR \fIR\('EP_BASE\fR
.RS 4
The default base directory for the system if
\fB\-d\fR
\fIHOME_DIR\fR
is not specified\&.
\fIBASE_DIR\fR
is concatenated with the account name to define the home directory\&. If the
\fB\-m\fR
option is not used,
\fIBASE_DIR\fR
must exist\&.
.sp
If this option is not specified,
\fBuseradd\fR
will use the base directory specified by the
\fBHOME\fR
variable in
/etc/default/useradd, or
/home
by default\&.
.RE
.PP
\fB\-c\fR, \fB\-\-comment\fR \fICOMMENTAIRE\fR
.RS 4
Toute cha\(^ine de texte\&. C\'est g\('en\('eralement une description courte du compte, elle est actuellement utilis\('ee comme champ pour le nom complet de l\'utilisateur\&.
.RE
.PP
\fB\-d\fR, \fB\-\-home\fR \fIR\('EP_PERSO\fR
.RS 4
Le nouvel utilisateur sera cr\('e\('e en utilisant
\fIR\('EP_PERSO\fR
comme valeur de r\('epertoire de connexion de l\'utilisateur\&. Le comportement par d\('efaut est de concat\('ener
\fIUTILISATEUR\fR
au r\('epertoire
\fIR\('EP_BASE\fR, et de l\'utiliser en tant que nom de r\('epertoire de connexion\&. Il n\'est pas n\('ecessaire que le r\('epertoire
\fIR\('EP_PERSO\fR
existe mais il ne sera pas cr\('e\('e s\'il n\'existe pas\&.
.RE
.PP
\fB\-D\fR, \fB\-\-defaults\fR
.RS 4
See below, the subsection "Changing the default values"\&.
.RE
.PP
\fB\-e\fR, \fB\-\-expiredate\fR \fIDATE_FIN_VALIDIT\('E\fR
.RS 4
Date \(`a laquelle le compte utilisateur sera d\('esactiv\('e\&. La date est indiqu\('ee dans le format
\fIAAAA\-MM\-JJ\fR\&.
.sp
If not specified,
\fBuseradd\fR
will use the default expiry date specified by the
\fBEXPIRE\fR
variable in
/etc/default/useradd, or an empty string (no expiry) by default\&.
.RE
.PP
\fB\-f\fR, \fB\-\-inactive\fR \fIDUR\('EE_INACTIVIT\('E\fR
.RS 4
The number of days after a password expires until the account is permanently disabled\&. A value of 0 disables the account as soon as the password has expired, and a value of \-1 disables the feature\&.
.sp
If not specified,
\fBuseradd\fR
will use the default inactivity period specified by the
\fBINACTIVE\fR
variable in the
/etc/default/useradd, or \-1 by default\&.
.RE
.PP
\fB\-g\fR, \fB\-\-gid\fR \fIGROUPE\fR
.RS 4
The group name or number of the user\'s initial login group\&. The group name must exist\&. A group number must refer to an already existing group\&.
.sp
If not specified, the bahavior of
\fBuseradd\fR
will depend on the
\fBUSERGROUPS_ENAB\fR
variable in
/etc/login\&.defs\&. If this variable is set to
\fIyes\fR
(or
\fB\-U/\-\-user\-group\fR
is specified on the command line), a group will be created for the user, with the same name as her loginname\&. If the variable is set to
\fIno\fR
(or
\fB\-N/\-\-no\-user\-group\fR
is specified on the command line), useradd will set the primary group of the new user to the value specified by the
\fBGROUP\fR
variable in
/etc/default/useradd, or 100 by default\&.
.RE
.PP
\fB\-G\fR, \fB\-\-groups\fR \fIGROUPE1\fR[\fI,GROUPE2,\&.\&.\&.\fR[\fI,GROUPEN\fR]]]
.RS 4
Liste de groupes suppl\('ementaires auxquels appartient \('egalement l\'utilisateur\&. Chaque groupe est s\('epar\('e du suivant par une virgule, sans espace entre eux\&. Les groupes sont soumis aux m\(^emes restrictions que celles de l\'option
\fB\-g\fR\&. Le comportement par d\('efaut pour l\'utilisateur est de n\'appartenir qu\'au groupe initial\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Afficher un message d\'aide et quitter\&.
.RE
.PP
\fB\-k\fR, \fB\-\-skel\fR \fISKEL_DIR\fR
.RS 4
The skeleton directory, which contains files and directories to be copied in the user\'s home directory, when the home directory is created by
\fBuseradd\fR\&.
.sp
This option is only valid if the
\fB\-m\fR
(or
\fB\-\-create\-home\fR) option is specified\&.
.sp
If this option is not set, the skeleton directory is defined by the
\fBSKEL\fR
variable in
/etc/default/useradd
or, by default,
/etc/skel\&.
.RE
.PP
\fB\-K\fR, \fB\-\-key\fR \fICL\('E\fR=\fIVALEUR\fR
.RS 4
Overrides
/etc/login\&.defs
defaults (UID_MIN, UID_MAX, UMASK, PASS_MAX_DAYS and others)\&.

Example:
\fB\-K \fR\fIPASS_MAX_DAYS\fR=\fI\-1\fR
can be used when creating system account to turn off password ageing, even though system account has no password at all\&. Multiple
\fB\-K\fR
options can be specified, e\&.g\&.:
\fB\-K \fR
\fIUID_MIN\fR=\fI100\fR
\fB \-K \fR
\fIUID_MAX\fR=\fI499\fR
.sp
Note\ \&:
\fB\-K\fR
\fIUID_MIN\fR=\fI10\fR,\fIUID_MAX\fR=\fI499\fR
ne fonctionne pas pour l\'instant\&.
.RE
.PP
\fB\-l\fR, \fB\-\-no\-log\-init\fR
.RS 4
Do not add the user to the lastlog and faillog databases\&.
.sp
By default, the user\'s entries in the lastlog and faillog databases are resetted to avoid reusing the entry from a previously deleted user\&.
.RE
.PP
\fB\-m\fR, \fB\-\-create\-home\fR
.RS 4
Create the user\'s home directory if it does not exist\&. The files and directories contained in the skeleton directory (which can be defined with the
\fB\-k\fR
option) will be copied to the home directory\&.
.sp
By default, no home directories are created\&.
.RE
.PP
\fB\-M\fR
.RS 4
Do no create the user\'s home directory, even if the system wide setting from
/etc/login\&.defs
(\fBCREATE_HOME\fR) is set to
\fIyes\fR\&.
.RE
.PP
\fB\-N\fR, \fB\-\-no\-user\-group\fR
.RS 4
Do not create a group with the same name as the user, but add the user to the group specified by the
\fB\-g\fR
option or by the GROUP variable in
/etc/default/useradd\&.
.sp
The default behavior (if the
\fB\-g\fR,
\fB\-N\fR, and
\fB\-U\fR
options are not specified) is defined by the
\fBUSERGROUPS_ENAB\fR
variable in
/etc/login\&.defs\&.
.RE
.PP
\fB\-o\fR, \fB\-\-non\-unique\fR
.RS 4
Permet de cr\('eer un compte d\'utilisateur avec un identifiant (\(Fo\ \&UID\ \&\(Fc) dupliqu\('e (non unique)\&.
.sp
This option is only valid in combination with the
\fB\-o\fR
option\&.
.RE
.PP
\fB\-p\fR, \fB\-\-password\fR \fIMOT_DE_PASSE\fR
.RS 4
Le mot de passe chiffr\('e, comme renvoy\('e par
\fBcrypt\fR(3)\&. Le comportement par d\('efaut est de d\('esactiver le compte\&.
.sp

\fBNote:\fR
This option is not recommended because the password (or encrypted password) will be visible by users listing the processes\&.
.RE
.PP
\fB\-r\fR, \fB\-\-system\fR
.RS 4
Create a system account\&.
.sp
System users will be created with no aging information in
/etc/shadow, and their numeric identifiers are choosen in the
\fBSYS_UID_MIN\fR\-\fBSYS_UID_MAX\fR
range, defined in
/etc/login\&.defs, instead of
\fBUID_MIN\fR\-\fBUID_MAX\fR
(and their
\fBGID\fR
counterparts for the creation of groups)\&.
.sp
Note that
\fBuseradd\fR
will not create a home directory for such an user, regardless of the default setting in
/etc/login\&.defs
(\fBCREATE_HOME\fR)\&. You have to specify the
\fB\-m\fR
options if you want a home directory for a system account to be created\&.
.RE
.PP
\fB\-s\fR, \fB\-\-shell\fR \fIINTERPR\('ETEUR\fR
.RS 4
The name of the user\'s login shell\&. The default is to leave this field blank, which causes the system to select the default login shell specified by the
\fBSHELL\fR
variable in
/etc/default/useradd, or an empty string by default\&.
.RE
.PP
\fB\-u\fR, \fB\-\-uid\fR \fIUID\fR
.RS 4
La valeur num\('erique de l\'identifiant de l\'utilisateur\&. Cette valeur doit \(^etre unique, \(`a moins que l\'option
\fB\-o\fR
ne soit utilis\('ee\&. La valeur ne doit pas \(^etre n\('egative\&. Le comportement par d\('efaut est d\'utiliser la plus petite valeur d\'identifiant plus grande que 999, et plus grande que celle des identifiants de tous les autres utilisateurs\&. Les valeurs comprises entre 0 et 999 sont g\('en\('eralement r\('eserv\('ees pour les comptes syst\(`emes\&.
.RE
.PP
\fB\-U\fR, \fB\-\-user\-group\fR
.RS 4
Create a group with the same name as the user, and add the user to this group\&.
.sp
The default behavior (if the
\fB\-g\fR,
\fB\-N\fR, and
\fB\-U\fR
options are not specified) is defined by the
\fBUSERGROUPS_ENAB\fR
variable in
/etc/login\&.defs\&.
.RE
.PP
\fB\-Z\fR, \fB\-\-selinux\-user\fR \fISEUSER\fR
.RS 4
The SELinux user for the user\'s login\&. The default is to leave this field blank, which causes the system to select the default SELinux user\&.
.RE
.SS "Modifier les valeurs par d\('efaut"
.PP
When invoked with only the
\fB\-D\fR
option,
\fBuseradd\fR
will display the current default values\&. When invoked with
\fB\-D\fR
plus other options,
\fBuseradd\fR
will update the default values for the specified options\&. Valid default\-changing options are:
.PP
\fB\-b\fR, \fB\-\-base\-dir\fR \fIR\('EP_BASE\fR
.RS 4
The path prefix for a new user\'s home directory\&. The user\'s name will be affixed to the end of
\fIBASE_DIR\fR
to form the new user\'s home directory name, if the
\fB\-d\fR
option is not used when creating a new account\&.
.sp
This option sets the
\fBHOME\fR
variable in
/etc/default/useradd\&.
.RE
.PP
\fB\-e\fR, \fB\-\-expiredate\fR \fIDATE_FIN_VALIDIT\('E\fR
.RS 4
Date \(`a laquelle le compte utilisateur sera d\('esactiv\('e\&.
.sp
This option sets the
\fBEXPIRE\fR
variable in
/etc/default/useradd\&.
.RE
.PP
\fB\-f\fR, \fB\-\-inactive\fR \fIDUR\('EE_INACTIVIT\('E\fR
.RS 4
Nombre de jours apr\(`es la fin de validit\('e d\'un mot de passe avant que le compte ne soit d\('esactiv\('e\&.
.sp
This option sets the
\fBINACTIVE\fR
variable in
/etc/default/useradd\&.
.RE
.PP
\fB\-g\fR, \fB\-\-gid\fR \fIGROUPE\fR
.RS 4
The group name or ID for a new user\'s initial group (when the
\fB\-N/\-\-no\-user\-group\fR
is used or when the
\fBUSERGROUPS_ENAB\fR
variable is set to
\fIno\fR
in
/etc/login\&.defs\&. The named group must exist, and a numerical group ID must have an existing entry\&.
.sp
This option sets the
\fBGROUP\fR
variable in
/etc/default/useradd\&.
.RE
.PP
\fB\-s\fR, \fB\-\-shell\fR \fIINTERPR\('ETEUR\fR
.RS 4
The name of a new user\'s login shell\&.
.sp
This option sets the
\fBSHELL\fR
variable in
/etc/default/useradd\&.
.RE
.SH "NOTES"
.PP
The system administrator is responsible for placing the default user files in the
/etc/skel/
directory (or any other skeleton directory specified in
/etc/default/useradd
or on the command line)\&.
.SH "AVERTISSEMENTS"
.PP
You may not add a user to a NIS or LDAP group\&. This must be performed on the corresponding server\&.
.PP
Similarly, if the username already exists in an external user database such as NIS or LDAP,
\fBuseradd\fR
will deny the user account creation request\&.
.PP
Usernames must begin with a lower case letter or an underscore, and only lower case letters, underscores, dashes, and dollar signs may follow\&. In regular expression terms: [a\-z_][a\-z0\-9_\-]*[$]?
.PP
Usernames may only be up to 32 characters long\&.
.SH "CONFIGURATION"
.PP
The following configuration variables in
/etc/login\&.defs
change the behavior of this tool:
.PP
\fBCREATE_HOME\fR (boolean)
.RS 4
Indiquer si un r\('epertoire personnel doit \(^etre cr\('e\('e par d\('efaut pour les nouveaux utilisateurs\&.
.sp
Ce r\('eglage ne s\'applique pas pour les utilisateurs syst\(`eme, et peut \(^etre annul\('e sur la ligne de commande\&.
.RE
.PP
\fBGID_MAX\fR (number), \fBGID_MIN\fR (number)
.RS 4
Range of group IDs used for the creation of regular groups by
\fBuseradd\fR,
\fBuseradd\fR, or
\fBnewusers\fR\&.
.RE
.PP
\fBMAIL_DIR\fR (string)
.RS 4
R\('epertoire d\'attente des courriels (\(Fo\ \&mail spool directory\ \&\(Fc)\&. Ce param\(`etre est n\('ecessaire pour manipuler les bo\(^ites \(`a lettres lorsque le compte d\'un utilisateur est modifi\('e ou supprim\('e\&. S\'il n\'est pas sp\('ecifi\('e, une valeur par d\('efaut d\('efinie \(`a la compilation est utilis\('ee\&.
.RE
.PP
\fBMAIL_FILE\fR (string)
.RS 4
D\('efinit l\'emplacement des bo\(^ites aux lettres des utilisateurs relativement \(`a leur r\('epertoire personnel\&.
.RE
.PP
Les param\(`etres
\fBMAIL_DIR\fR
et
\fBMAIL_FILE\fR
sont utilis\('ees par
\fBuseradd\fR,
\fBusermod\fR, et
\fBuserdel\fR
pour cr\('eer, d\('eplacer, ou supprimer les bo\(^ites aux lettres des utilisateurs\&.
.PP
If
\fBMAIL_CHECK_ENAB\fR
is set to
\fIyes\fR, they are also used to define the
\fBMAIL\fR
environment variable\&.
.PP
\fBMAX_MEMBERS_PER_GROUP\fR (nombre)
.RS 4
Nombre maximum de membres par entr\('ee de groupe\&. Lorsque le maximum est atteint, une nouvelle entr\('ee de groupe (ligne) est d\('emarr\('ee dans
/etc/group
(avec le m\(^eme nom, m\(^eme mot de passe, et m\(^eme GID)\&.
.sp
La valeur par d\('efaut est 0, ce qui signifie qu\'il n\'y a pas de limites pour le nombre de membres dans un groupe\&.
.sp
Cette fonctionnalit\('e (groupe d\('ecoup\('e) permet de limiter la longueur des lignes dans le fichier de groupes\&. Ceci est utile pour s\'assurer que les lignes pour les groupes NIS ne sont pas plus grandes que 1024 caract\(`eres\&.
.sp
Si vous avez besoin de fixer cette limite, vous pouvez utiliser 25\&.
.sp
Note: split groups may not be supported by all tools (even in the Shadow toolsuite)\&. You should not use this variable unless you really need it\&.
.RE
.PP
\fBPASS_MAX_DAYS\fR (number)
.RS 4
Nombre maximum de jours de validit\('e d\'un mot de passe\&. Apr\(`es cette dur\('ee, une modification du mot de passe est obligatoire\&. S\'il n\'est pas pr\('ecis\('e, la valeur de \-1 est utilis\('ee (ce qui enl\(`eve toute restriction)\&.
.RE
.PP
\fBPASS_MIN_DAYS\fR (number)
.RS 4
Nombre minimum de jours autoris\('e avant la modification d\'un mot de passe\&. Toute tentative de modification du mot de passe avant cette dur\('ee est rejet\('ee\&. S\'il n\'est pas pr\('ecis\('e, la valeur de \-1 est utilis\('ee (ce qui enl\(`eve toute restriction)\&.
.RE
.PP
\fBPASS_WARN_AGE\fR (number)
.RS 4
Nombre de jours durant lesquels l\'utilisateur recevra un avertissement avant que son mot de passe n\'arrive en fin de validit\('e\&. Une valeur n\('egative signifie qu\'aucun avertissement n\'est donn\('e\&. S\'il n\'est pas pr\('ecis\('e, aucun avertissement n\'est donn\('e\&.
.RE
.PP
\fBSYS_GID_MAX\fR (number), \fBSYS_GID_MIN\fR (number)
.RS 4
Range of group IDs used for the creation of system groups by
\fBuseradd\fR,
\fBgroupadd\fR, or
\fBnewusers\fR\&.
.RE
.PP
\fBSYS_UID_MAX\fR (number), \fBSYS_UID_MIN\fR (number)
.RS 4
Range of user IDs used for the creation of system users by
\fBuseradd\fR
or
\fBnewusers\fR\&.
.RE
.PP
\fBUID_MAX\fR (number), \fBUID_MIN\fR (number)
.RS 4
Range of user IDs used for the creation of regular users by
\fBuseradd\fR
or
\fBnewusers\fR\&.
.RE
.PP
\fBUMASK\fR (number)
.RS 4
The file mode creation mask is initialized to this value\&. If not specified, the mask will be initialized to 022\&.
.sp

\fBuseradd\fR
and
\fBnewusers\fR
use this mask to set the mode of the home directory they create
.sp
It is also used by
\fBlogin\fR
to define users\' initial umask\&. Note that this mask can be overriden by the user\'s GECOS line (if
\fBQUOTAS_ENAB\fR
is set) or by the specification of a limit with the
\fIK\fR
identifier in
\fBlimits\fR(5)\&.
.RE
.PP
\fBUSERGROUPS_ENAB\fR (boolean)
.RS 4
Enable setting of the umask group bits to be the same as owner bits (examples: 022 \-> 002, 077 \-> 007) for non\-root users, if the uid is the same as gid, and username is the same as the primary group name\&.
.sp
If set to
\fIyes\fR,
\fBuserdel\fR
will remove the user\'s group if it contains no more members, and
\fBuseradd\fR
will create by default a group with the name of the user\&.
.RE
.SH "FICHIERS"
.PP
/etc/passwd
.RS 4
Informations sur les comptes des utilisateurs\&.
.RE
.PP
/etc/shadow
.RS 4
Informations s\('ecuris\('ees sur les comptes utilisateurs\&.
.RE
.PP
/etc/group
.RS 4
Informations sur les groupes\&.
.RE
.PP
/etc/gshadow
.RS 4
Informations s\('ecuris\('ees sur les groupes\&.
.RE
.PP
/etc/default/useradd
.RS 4
Valeurs par d\('efaut pour la cr\('eation de comptes\&.
.RE
.PP
/etc/skel/
.RS 4
R\('epertoire contenant les fichiers par d\('efaut\&.
.RE
.PP
/etc/login\&.defs
.RS 4
Configuration de la suite des mots de passe cach\('es \(Fo\ \&shadow password\ \&\(Fc\&.
.RE
.SH "VALEURS DE RETOUR"
.PP
La commande
\fBuseradd\fR
retourne les valeurs suivantes en quittant\ \&:
.PP
\fI0\fR
.RS 4
succ\(`es
.RE
.PP
\fI1\fR
.RS 4
impossible de mettre \(`a jour le fichier des mots de passe
.RE
.PP
\fI2\fR
.RS 4
erreur de syntaxe
.RE
.PP
\fI3\fR
.RS 4
param\(`etre non valable pour l\'option
.RE
.PP
\fI4\fR
.RS 4
UID d\('ej\(`a utilis\('e (et pas d\'option
\fB\-o\fR)
.RE
.PP
\fI6\fR
.RS 4
le groupe sp\('ecifi\('e n\'existe pas
.RE
.PP
\fI9\fR
.RS 4
nom d\'utilisateur d\('ej\(`a utilis\('e
.RE
.PP
\fI10\fR
.RS 4
impossible de mettre \(`a jour le fichier des groupes
.RE
.PP
\fI12\fR
.RS 4
impossible de cr\('eer le r\('epertoire personnel
.RE
.PP
\fI13\fR
.RS 4
impossible de cr\('eer le r\('epertoire d\'attente des courriels
.RE
.SH "VOIR AUSSI"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBcrypt\fR(3),
\fBgroupadd\fR(8),
\fBgroupdel\fR(8),
\fBgroupmod\fR(8),
\fBlogin.defs\fR(5),
\fBnewusers\fR(8),
\fBuserdel\fR(8),
\fBusermod\fR(8)\&.
